server:
  port: 80
#整合mybatis
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf-8
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.yuan.mybatisday01.vo

logging:
  level:
    com.yuan.mybatisday01.controller: trace